### ISSUE TITLE
togeojson doesn't work with Electron 17.1.0

### ISSUE THREAD

**Issue by tris-g** [mapbox/togeojson#175]
Hi, I'm trying to use togeojson on an Electron app using `npm i @mapbox/togeojson --save --build-from-source` with env variables set for Electron build. However it isn't finding togeojson:

`Uncaught Error: Cannot find module 'togeojson'`

If someone could help that would be great. Thanks.

**Comment by tris-g** [comment]
I needed to do `require('@mapbox/togeojson')`
